### ISSUE TITLE
Bug with Add/Undo

### ISSUE THREAD

**Issue by Fullymetal** [Seneral/UndoPro#1]
Hi,

Thank you for your Undo/redo system.
I think i find a bug, when i do : 
- Add Record
- Add Record
- Undo
- Undo
- Add
- Undo

The last Undo create 2 action identical

I join a text file with the relativeStackPos : 
[RelativeStackPos.txt](https://github.com/Seneral/UndoPro/files/379446/RelativeStackPos.txt)

Cheers,

Fully

**Comment by Seneral** [comment]
Hi Fully,
thanks for the note:)
I'm sorry for the late reply, my phone broke saturday so I can't receive instant notifications anymore:(
I'll take a look at it right now!

**Comment by Seneral** [comment]
Was able to repoduce it and it should be fixed in 0b8f499 :)
