### ISSUE TITLE
GetRecordsInternal has been changed in 2021.2.0b

### ISSUE THREAD

**Issue by Mannilie** [Seneral/UndoPro#4]
Unity has updated their internal methods for the Undo class in the newest iteration of their engine (2021.2.0b).

It appears that the internal method that UndoPro relies on 'GetRecordsInternal' has been renamed to 'GetTimelineRecordsInternal'.
![image](https://user-images.githubusercontent.com/9096217/127755913-4be7cc52-bdc2-4292-bbb1-c32f3dc71a29.png)

Changing the keyword does appear to work in the latest version of unity, However a new bug has appeared when you perform an Undo operation using Undo Pro.
![image](https://user-images.githubusercontent.com/9096217/127755921-da4363ec-204d-4785-84b8-2e251f1f63f6.png)

**Comment by Mannilie** [comment]
I actually found out what caused that second error. 
It's totally unrelated but it seems to only happen if users call 'Undo.RegisterCreatedObjectUndo' in any events other than EditorApplication calls. 

I fixed that issue by simply ensuring that I call Undo.RegisterCreatedObjectUndo in an EditorApplication method.

Please see linked Pull Request for the result of this fix: [Added support for Unity 2021.2.0b #5](https://github.com/Seneral/UndoPro/pull/5)

**Comment by Seneral** [comment]
Hey, first of thank you so much for taking a look at it and fixing it!
And sorry for not seeing to this sooner.

Though I truly hope the "Undo.RegisterCreatedObjectUndo" only working in an "EditorApplication" is going to be fixed - unless that also includes custom custom inspectors, EditorWindows, etc.
I'm currently in a very busy period so I don't even have time to test it unfortunately.

**Comment by Mannilie** [comment]
Hey mate,
Not a problem at all! I really enjoy using this system. Just tried to use it in the latest and found Unity being Unity and updating the most obscure internal things again! haha.

Thanks for merging my pull request! :)

**Comment by J-Ponzo** [comment]
@Mannilie Thank you ! You saved me
@Seneral  Thank you ! Your tools are awesome.
