### ISSUE TITLE
 "ArgumentException: method arguments are incompatible" on Unity 2021.2.x

### ISSUE THREAD

**Issue by J-Ponzo** [Seneral/UndoPro#6]
Hi, first of all thanks for the awesome work !

I have an issue with Unity 2021.2.x. As soon as the project opens, I have error endlessly thrown in the console. The error is : 

ArgumentException: method arguments are incompatible
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) (at <00c558282d074245ab3496e2d108079b>:0)
System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure) (at <00c558282d074245ab3496e2d108079b>:0)
System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method) (at <00c558282d074245ab3496e2d108079b>:0)
UndoPro.UndoProManager.EnableUndoPro () (at Library/PackageCache/com.seneral.undopro@6a77de2ea6/UndoProManager.cs:83)
UndoPro.UndoProManager..cctor () (at Library/PackageCache/com.seneral.undopro@6a77de2ea6/UndoProManager.cs:64)
Rethrow as TypeInitializationException: The type initializer for 'UndoPro.UndoProManager' threw an exception.
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <948074e677924ec29383d02747cdda34>:0)

Issue occured on :
- 2021.2.4f1 
- 2021.2.0f1

But is not present on :
- 2021.1.15f1

![Capture](https://user-images.githubusercontent.com/32590977/143583950-58ab0e64-0d7b-4b8f-b212-4e725c2e8192.PNG)

**Comment by J-Ponzo** [comment]
Sorry !

I just saw the issue was already reported and solved here : https://github.com/Seneral/UndoPro/issues/4
Like explained, I replaced 'GetRecordsInternal' with 'GetTimelineRecordsInternal' on the line before the error and it's ok now.

**Comment by Seneral** [comment]
Sorry, I was intending on repackaging it for a while now, but I just don't have the time for at least another week to come.
